// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCY0sV54prBkohdMzHxFUYG12DJeJ2JKEc',
    appId: '1:495363110160:web:bd1ed5e39dbf0569f16195',
    messagingSenderId: '495363110160',
    projectId: 'todo-app-5cb2b',
    authDomain: 'todo-app-5cb2b.firebaseapp.com',
    storageBucket: 'todo-app-5cb2b.appspot.com',
    measurementId: 'G-4QVW4RG8TE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTVOrbCGCCBe50Y97nVYm6NyHufQZgJkM',
    appId: '1:495363110160:android:d08339572fb8fb19f16195',
    messagingSenderId: '495363110160',
    projectId: 'todo-app-5cb2b',
    storageBucket: 'todo-app-5cb2b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZ0cu-7fBxokHgShGoFPEq3hciSVtcolk',
    appId: '1:495363110160:ios:aa1c69a9e0a020adf16195',
    messagingSenderId: '495363110160',
    projectId: 'todo-app-5cb2b',
    storageBucket: 'todo-app-5cb2b.appspot.com',
    iosBundleId: 'com.example.flutterTaskPlannerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCY0sV54prBkohdMzHxFUYG12DJeJ2JKEc',
    appId: '1:495363110160:web:00f79461e8498271f16195',
    messagingSenderId: '495363110160',
    projectId: 'todo-app-5cb2b',
    authDomain: 'todo-app-5cb2b.firebaseapp.com',
    storageBucket: 'todo-app-5cb2b.appspot.com',
    measurementId: 'G-0TNP16M56X',
  );
}
